BOT_TOKEN = "1339981204:AAGfBHbWW4Bycellhh4cqWtgD1YAwUmF7WQ"

NAME_START_MENU = "STATE_START_MENU"
NAME_HELLO_MENU = "STATE_HELLO_MENU"
NAME_ADD_MENU = "STATE_ADD_MENU"
NAME_ABOUT_MENU = "STATE_ABOUT_MENU"
NAME_HELP_MENU = "STATE_HELP_MENU"
NAME_PARTNERSHIP_MENU = "STATE_PARTNERSHIP_MENU"
NAME_SEARCH_MENU = "STATE_SEARCH_MENU"
